elastic: localhost:9300

tables:
  -
    path: /apps/test_table
    changelog: /apps/test_changelog:test
    indexedFields:
      - first_name
#  -
#    path: /apps/test_table2
#    changelog: /apps/test_changelog2:test2
#    indexedFields:
#      - name
#      - surname
